name: K6 Load Test

on:
  push:
    branches: [main]

jobs:
  performance-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask App
        run: nohup python app.py & sleep 5

      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run K6 Load Test
        run: k6 run test.k6.js
